export const ROLES = [
  "SUPER_ADMIN",
  "ADMINISTRADOR",
  "GERENTE",
  "SUPERVISOR",
  "FACTURACION",
  "CAJA",
  "COBRADOR",
  "LECTOR",
  "LECTORISTA",
  "INSTALADOR",
  "TECNICO",
  "CONSULTA",
] as const;

export type RoleCode = (typeof ROLES)[number];

export const PERMISSIONS = [
  "dashboard.ver",
  "clientes.ver",
  "clientes.crear",
  "clientes.editar",
  "clientes.baja",
  "conexiones.ver",
  "conexiones.crear",
  "conexiones.editar",
  "medidores.ver",
  "medidores.crear",
  "medidores.editar",
  "lecturas.ver",
  "lecturas.crear",
  "lecturas.editar",
  "lecturas.aprobar",
  "instalaciones.ver",
  "instalaciones.registrar",
  "tarifas.ver",
  "tarifas.crear",
  "tarifas.editar",
  "periodos.ver",
  "periodos.crear",
  "periodos.editar",
  "periodos.reabrir",
  "boletas.ver",
  "boletas.crear",
  "boletas.emitir",
  "facturas.ver",
  "facturas.crear",
  "facturas.emitir",
  "facturas.anular",
  "timbrados.ver",
  "timbrados.crear",
  "timbrados.editar",
  "sifen.enviar",
  "sifen.consultar",
  "pagos.ver",
  "pagos.crear",
  "pagos.anular",
  "cobranza.ver",
  "cobranza.recorrido",
  "cuentas.ver",
  "morosidad.ver",
  "morosidad.gestionar",
  "suspensiones.ver",
  "suspensiones.crear",
  "desconexiones.programar",
  "desconexiones.ejecutar",
  "reconexiones.ver",
  "reconexiones.crear",
  "reclamos.ver",
  "reclamos.crear",
  "reclamos.editar",
  "inventario.ver",
  "inventario.movimiento",
  "proveedores.ver",
  "proveedores.crear",
  "proveedores.editar",
  "gastos.ver",
  "gastos.crear",
  "reportes.ver",
  "mapa.ver",
  "usuarios.ver",
  "usuarios.crear",
  "usuarios.editar",
  "roles.ver",
  "roles.editar",
  "notificaciones.ver",
  "auditoria.ver",
  "configuracion.ver",
  "configuracion.editar",
  "regulacion.ver",
  "regulacion.editar",
  "sync.resolver",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Record<RoleCode, readonly Permission[]> = {
  SUPER_ADMIN: PERMISSIONS,
  ADMINISTRADOR: PERMISSIONS.filter((p) => p !== "periodos.reabrir"),
  GERENTE: PERMISSIONS.filter(
    (p) =>
      !p.startsWith("usuarios.") &&
      !p.startsWith("roles.") &&
      p !== "configuracion.editar" &&
      p !== "timbrados.editar",
  ),
  SUPERVISOR: [
    "dashboard.ver",
    "clientes.ver",
    "conexiones.ver",
    "medidores.ver",
    "lecturas.ver",
    "lecturas.crear",
    "lecturas.editar",
    "lecturas.aprobar",
    "instalaciones.ver",
    "boletas.ver",
    "cuentas.ver",
    "morosidad.ver",
    "morosidad.gestionar",
    "suspensiones.ver",
    "suspensiones.crear",
    "desconexiones.programar",
    "desconexiones.ejecutar",
    "reconexiones.ver",
    "reconexiones.crear",
    "reclamos.ver",
    "reclamos.crear",
    "reclamos.editar",
    "mapa.ver",
    "reportes.ver",
    "notificaciones.ver",
    "sync.resolver",
  ],
  FACTURACION: [
    "dashboard.ver",
    "clientes.ver",
    "conexiones.ver",
    "medidores.ver",
    "lecturas.ver",
    "lecturas.aprobar",
    "tarifas.ver",
    "periodos.ver",
    "periodos.crear",
    "periodos.editar",
    "boletas.ver",
    "boletas.crear",
    "boletas.emitir",
    "facturas.ver",
    "facturas.crear",
    "facturas.emitir",
    "facturas.anular",
    "timbrados.ver",
    "sifen.enviar",
    "sifen.consultar",
    "cuentas.ver",
    "cobranza.ver",
    "pagos.ver",
    "reportes.ver",
  ],
  CAJA: [
    "dashboard.ver",
    "clientes.ver",
    "boletas.ver",
    "facturas.ver",
    "pagos.ver",
    "pagos.crear",
    "pagos.anular",
    "cobranza.ver",
    "cuentas.ver",
    "morosidad.ver",
  ],
  COBRADOR: [
    "dashboard.ver",
    "clientes.ver",
    "conexiones.ver",
    "boletas.ver",
    "pagos.ver",
    "pagos.crear",
    "cobranza.ver",
    "cobranza.recorrido",
    "cuentas.ver",
    "morosidad.ver",
    "mapa.ver",
    "notificaciones.ver",
  ],
  LECTOR: [
    "dashboard.ver",
    "clientes.ver",
    "conexiones.ver",
    "medidores.ver",
    "lecturas.ver",
    "lecturas.crear",
    "mapa.ver",
    "notificaciones.ver",
  ],
  LECTORISTA: [
    "dashboard.ver",
    "clientes.ver",
    "conexiones.ver",
    "medidores.ver",
    "lecturas.ver",
    "lecturas.crear",
    "mapa.ver",
    "notificaciones.ver",
  ],
  INSTALADOR: [
    "dashboard.ver",
    "clientes.ver",
    "conexiones.ver",
    "medidores.ver",
    "instalaciones.ver",
    "instalaciones.registrar",
    "mapa.ver",
    "notificaciones.ver",
  ],
  TECNICO: [
    "clientes.ver",
    "conexiones.ver",
    "medidores.ver",
    "instalaciones.ver",
    "instalaciones.registrar",
    "reclamos.ver",
    "reclamos.editar",
    "suspensiones.ver",
    "suspensiones.crear",
    "desconexiones.ejecutar",
    "reconexiones.ver",
    "reconexiones.crear",
    "mapa.ver",
    "notificaciones.ver",
  ],
  CONSULTA: [
    "dashboard.ver",
    "clientes.ver",
    "conexiones.ver",
    "medidores.ver",
    "lecturas.ver",
    "boletas.ver",
    "facturas.ver",
    "cuentas.ver",
    "cobranza.ver",
    "pagos.ver",
    "reportes.ver",
    "mapa.ver",
  ],
};
