/** Departamentos y distritos de Paraguay (capital Asunción como departamento). */

export const PARAGUAY_DEPARTMENTS = [
  "Asunción",
  "Concepción",
  "San Pedro",
  "Cordillera",
  "Guairá",
  "Caaguazú",
  "Caazapá",
  "Itapúa",
  "Misiones",
  "Paraguarí",
  "Alto Paraná",
  "Central",
  "Ñeembucú",
  "Amambay",
  "Canindeyú",
  "Presidente Hayes",
  "Boquerón",
  "Alto Paraguay",
] as const;

export type ParaguayDepartment = (typeof PARAGUAY_DEPARTMENTS)[number];

export const PARAGUAY_CITIES: Record<ParaguayDepartment, string[]> = {
  Asunción: ["Asunción"],
  Concepción: [
    "Concepción",
    "Horqueta",
    "Loreto",
    "Belén",
    "Yby Yaú",
    "Azotey",
    "Sargento José Félix López",
    "San Carlos del Apa",
    "San Lázaro",
  ],
  "San Pedro": [
    "San Pedro de Ycuamandiyú",
    "Antequera",
    "Capiibary",
    "Choré",
    "General Elizardo Aquino",
    "General Isidoro Resquín",
    "Guayaibí",
    "Itacurubí del Rosario",
    "Liberación",
    "Lima",
    "Nueva Germania",
    "San Estanislao",
    "San Pablo",
    "Santa Rosa del Aguaray",
    "Tacuatí",
    "Unión",
    "25 de Diciembre",
    "Villa del Rosario",
    "Yataity del Norte",
    "Yrybucuá",
  ],
  Cordillera: [
    "Caacupé",
    "Altos",
    "Arroyos y Esteros",
    "Atyrá",
    "Caraguatay",
    "Emboscada",
    "Eusebio Ayala",
    "Isla Pucú",
    "Itacurubí de la Cordillera",
    "Juan de Mena",
    "Loma Grande",
    "Mbocayaty del Yhaguy",
    "Nueva Colombia",
    "Piribebuy",
    "Primero de Marzo",
    "San Bernardino",
    "Santa Elena",
    "Tobatí",
    "Valenzuela",
  ],
  Guairá: [
    "Villarrica",
    "Borja",
    "Capitán Mauricio José Troche",
    "Coronel Martínez",
    "Doctor Botrell",
    "Félix Pérez Cardozo",
    "General Eugenio A. Garay",
    "Independencia",
    "Itapé",
    "Iturbe",
    "José Fassardi",
    "Mbocayaty",
    "Natalicio Talavera",
    "Ñumí",
    "San Salvador",
    "Yataity",
    "Tebicuary",
  ],
  Caaguazú: [
    "Coronel Oviedo",
    "Caaguazú",
    "Carayaó",
    "Doctor Cecilio Báez",
    "Doctor J. Eulogio Estigarribia",
    "Doctor Juan Manuel Frutos",
    "José Domingo Ocampos",
    "La Pastora",
    "Mariscal Francisco Solano López",
    "Nueva Londres",
    "Raúl Arsenio Oviedo",
    "Repatriación",
    "R.I. 3 Corrales",
    "San Joaquín",
    "San José de los Arroyos",
    "Santa Rosa del Mbutuy",
    "Simón Bolívar",
    "Tres de Febrero",
    "Vaquería",
    "Yhú",
    "Tembiaporá",
    "Nueva Toledo",
  ],
  Caazapá: [
    "Caazapá",
    "Abaí",
    "Buena Vista",
    "Doctor Moisés S. Bertoni",
    "Fulgencio Yegros",
    "General Higinio Morínigo",
    "Maciel",
    "San Juan Nepomuceno",
    "Tavaí",
    "Yegros",
    "3 de Mayo",
  ],
  Itapúa: [
    "Encarnación",
    "Alto Verá",
    "Bella Vista",
    "Cambyretá",
    "Capitán Meza",
    "Capitán Miranda",
    "Carlos Antonio López",
    "Carmen del Paraná",
    "Coronel Bogado",
    "Edelira",
    "Fram",
    "General Artigas",
    "General Delgado",
    "Hohenau",
    "Itapúa Poty",
    "Jesús",
    "José Leandro Oviedo",
    "La Paz",
    "Mayor Otaño",
    "Natalio",
    "Nueva Alborada",
    "Obligado",
    "Pirapó",
    "San Cosme y Damián",
    "San Juan del Paraná",
    "San Pedro del Paraná",
    "San Rafael del Paraná",
    "Tomás Romero Pereira",
    "Trinidad",
    "Yatytay",
  ],
  Misiones: [
    "San Juan Bautista",
    "Ayolas",
    "San Ignacio",
    "San Miguel",
    "San Patricio",
    "Santa María",
    "Santa Rosa",
    "Santiago",
    "Villa Florida",
    "Yabebyry",
  ],
  Paraguarí: [
    "Paraguarí",
    "Acahay",
    "Caapucú",
    "Carapeguá",
    "Escobar",
    "General Bernardino Caballero",
    "La Colmena",
    "Mbuyapey",
    "Pirayú",
    "Quiindy",
    "Quyquyhó",
    "San Roque González de Santa Cruz",
    "Sapucai",
    "Tebicuarymí",
    "Yaguarón",
    "Ybycuí",
    "Ybytymí",
  ],
  "Alto Paraná": [
    "Ciudad del Este",
    "Doctor Juan León Mallorquín",
    "Domingo Martínez de Irala",
    "Hernandarias",
    "Iruña",
    "Itakyry",
    "Juan Emilio O'Leary",
    "Los Cedrales",
    "Mbaracayú",
    "Minga Guazú",
    "Minga Porá",
    "Naranjal",
    "Ñacunday",
    "Presidente Franco",
    "San Alberto",
    "San Cristóbal",
    "Santa Fe del Paraná",
    "Santa Rita",
    "Santa Rosa del Monday",
    "Yguazú",
    "Tavapy",
    "Puerto Indio",
    "Doctor Raúl Peña",
  ],
  Central: [
    "Areguá",
    "Capiatá",
    "Fernando de la Mora",
    "Guarambaré",
    "Itá",
    "Itauguá",
    "Lambaré",
    "Limpio",
    "Luque",
    "Mariano Roque Alonso",
    "Ñemby",
    "Nueva Italia",
    "San Antonio",
    "San Lorenzo",
    "Villa Elisa",
    "Villeta",
    "Ypacaraí",
    "Ypané",
    "J. Augusto Saldivar",
  ],
  Ñeembucú: [
    "Pilar",
    "Alberdi",
    "Cerrito",
    "Desmochados",
    "General José Eduvigis Díaz",
    "Guazú Cuá",
    "Humaitá",
    "Isla Umbú",
    "Laureles",
    "Mayor José Dejesús Martínez",
    "Paso de Patria",
    "San Juan Bautista de Ñeembucú",
    "Tacuaras",
    "Villa Franca",
    "Villa Oliva",
    "Villalbín",
  ],
  Amambay: ["Pedro Juan Caballero", "Bella Vista", "Capitán Bado", "Zanja Pytá", "Karapaí"],
  Canindeyú: [
    "Salto del Guairá",
    "Corpus Christi",
    "Curuguaty",
    "General Francisco Caballero Álvarez",
    "Itanará",
    "Katueté",
    "La Paloma",
    "Nueva Esperanza",
    "Yasy Cañy",
    "Ybyrarobaná",
    "Ypejhú",
    "Yby Pytá",
    "Maracaná",
  ],
  "Presidente Hayes": [
    "Villa Hayes",
    "Benjamín Aceval",
    "Doctor José Falcón",
    "General José María Bruguez",
    "Nanawa",
    "Puerto Pinasco",
    "Teniente Primero Manuel Irala Fernández",
    "Teniente Esteban Martínez",
  ],
  Boquerón: ["Filadelfia", "Loma Plata", "Mariscal Estigarribia"],
  "Alto Paraguay": ["Fuerte Olimpo", "Bahía Negra", "Carmelo Peralta", "Puerto Casado"],
};

export function citiesForDepartment(department: string): string[] {
  return PARAGUAY_CITIES[department as ParaguayDepartment] ?? [];
}

export const DEPARTMENT_OPTIONS = PARAGUAY_DEPARTMENTS.map((value) => ({ value, label: value }));

export const CITY_OPTIONS_BY_DEPARTMENT: Record<string, Array<{ value: string; label: string }>> = Object.fromEntries(
  PARAGUAY_DEPARTMENTS.map((d) => [d, PARAGUAY_CITIES[d].map((c) => ({ value: c, label: c }))]),
);
